# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analise.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranalise.proto\x12\x07\x61nalise\"X\n\x10\x44\x61\x64osParaAnalise\x12\x0f\n\x07wavy_id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ta_inicio\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61ta_fim\x18\x04 \x01(\t\"I\n\x10ResultadoAnalise\x12\r\n\x05media\x18\x01 \x01(\x01\x12\x16\n\x0etotal_amostras\x18\x02 \x01(\x05\x12\x0e\n\x06resumo\x18\x03 \x01(\t\"@\n\tTipoMedia\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\r\n\x05media\x18\x02 \x01(\x01\x12\x16\n\x0etotal_amostras\x18\x03 \x01(\x05\"F\n\x17ResultadoAnalisePorTipo\x12+\n\x0fmedias_por_tipo\x18\x01 \x03(\x0b\x32\x12.analise.TipoMedia2\xa5\x01\n\x07\x41nalise\x12\x45\n\rAnalisarDados\x12\x19.analise.DadosParaAnalise\x1a\x19.analise.ResultadoAnalise\x12S\n\x14\x41nalisarDadosPorTipo\x12\x19.analise.DadosParaAnalise\x1a .analise.ResultadoAnalisePorTipoB\r\xaa\x02\nAnaliseRpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nAnaliseRpc'
  _globals['_DADOSPARAANALISE']._serialized_start=26
  _globals['_DADOSPARAANALISE']._serialized_end=114
  _globals['_RESULTADOANALISE']._serialized_start=116
  _globals['_RESULTADOANALISE']._serialized_end=189
  _globals['_TIPOMEDIA']._serialized_start=191
  _globals['_TIPOMEDIA']._serialized_end=255
  _globals['_RESULTADOANALISEPORTIPO']._serialized_start=257
  _globals['_RESULTADOANALISEPORTIPO']._serialized_end=327
  _globals['_ANALISE']._serialized_start=330
  _globals['_ANALISE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
